// <auto-generated />
using System;
using Flagging.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flagging.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231107141247_CollapsedReportedUserIdCommentIdArticleIntoOneFieldItemId")]
    partial class CollapsedReportedUserIdCommentIdArticleIntoOneFieldItemId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flagging.Data.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dolor totam minus eum ab recusandae autem id aut. Suscipit quia nesciunt ducimus officia consequatur repellat molestiae quia neque. Qui molestiae et voluptas sunt error. Cumque ipsam accusamus consequatur ut occaecati quod at. Animi eaque reprehenderit ut. Omnis sequi est et. Laudantium ea non perspiciatis unde autem. Similique repudiandae accusantium mollitia voluptas est.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Odit ducimus laboriosam deleniti in laudantium. Et sint id in id esse sit aut. Excepturi aut perferendis commodi est delectus expedita alias. Recusandae sit sed corrupti quod. Id voluptas similique reprehenderit autem quos ratione unde.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dolores sint necessitatibus ratione unde voluptatem sunt magni. Illum autem saepe ut qui voluptas qui fugit deleniti velit. Voluptatem nulla perferendis occaecati maxime voluptatem earum facilis corporis. Saepe neque eius at sed aut at corrupti tempore. Error nihil et magni pariatur quibusdam. Sunt dignissimos ex sed aut perferendis itaque hic qui. Commodi cupiditate aliquid et. Dolorum asperiores magni delectus quia praesentium asperiores.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Eos et et et quis soluta ut blanditiis expedita. Odio et totam culpa. Commodi optio saepe ipsum rerum velit in. Iusto rerum corrupti ut autem repudiandae fuga libero. Officia et incidunt et qui cupiditate qui. Nemo et tenetur et.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Facilis atque numquam aut commodi debitis. Praesentium excepturi eligendi tenetur quam est qui architecto hic ut. Aliquid temporibus at repellat iste rerum voluptatum modi tempore unde. Voluptatibus minima libero est asperiores omnis tenetur ut mollitia. Eveniet est ea eum in.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Enim voluptatem qui quo voluptatem consequatur. Et iste odio vel. Blanditiis et sapiente cumque laborum ea qui ut id. Illum neque occaecati laborum eum quas qui corporis numquam vel. Ut autem magnam omnis cumque. At consequuntur quia veniam qui sed. Et quaerat adipisci et et quae qui. Adipisci qui omnis amet possimus.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Consectetur provident nobis aut commodi provident nulla tempora aut. Minima fugit minus consequatur quis est eveniet expedita rerum. Aut eius autem et. Ratione vitae consequatur eos expedita veniam minus illo ut nobis. Et corporis itaque nulla asperiores laboriosam reprehenderit. Et in beatae rerum aspernatur.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Recusandae et aliquid quo rerum reiciendis voluptas natus amet qui. Veritatis et quaerat illum mollitia. Quae consectetur voluptatum natus quis sequi illo id alias. Qui excepturi aliquam eveniet cupiditate. Ut impedit consequatur est.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Non sunt sed sit reiciendis quia et officia architecto et. Doloribus voluptatum cupiditate qui labore odit eius ducimus. Ratione itaque sapiente est odio ab. Voluptatibus qui iure dignissimos rerum sit aut sequi. Eos commodi in labore molestiae qui sed.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Repudiandae amet quaerat quo sed accusantium corrupti autem dolor. Harum consequatur consequatur velit. Aut inventore sit occaecati distinctio hic ex est soluta. Impedit et ut adipisci corrupti cum. Id rerum alias aut. Voluptates nesciunt voluptas odit minus et unde dolorum. Accusantium iste quas eveniet voluptates ea eum vel dolores.",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "Possimus illum et eos quasi. Eius sint ipsa sint dignissimos qui consequatur beatae veniam. Voluptatum amet maxime laudantium fuga voluptatem inventore mollitia. At nihil unde et aut porro fugiat fugit ut voluptatem. Aut consequatur rerum dolores est repellendus nulla aut.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Description = "Voluptates ut eveniet nam sed iste. Dolor enim reprehenderit quis cupiditate omnis eos. Porro et ut odit et dolores. Est aut impedit dolores eum soluta deserunt aliquid. Quos totam facere debitis fugit. Voluptatibus dolor rerum deleniti sint corporis voluptatum sunt ut.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Description = "Esse nostrum qui dolores expedita ipsa aspernatur omnis. Ea ea quaerat sunt qui odio sed mollitia. Dicta possimus quam officia odio pariatur quasi aut ullam. Ut quia vitae voluptas enim ut et. Itaque dolorem nesciunt sed non quasi. Est molestias dicta culpa odit qui eaque itaque inventore.",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sapiente aut cum sint iusto aliquam doloribus modi. Velit ea architecto eveniet. Non molestiae delectus aut nulla cupiditate vitae quia. Voluptatem rerum vel rerum consectetur sequi. Consequatur repellendus porro omnis. Autem doloremque eius quod. Amet a et beatae non qui repellat.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Description = "Placeat eos eveniet rerum laboriosam. Qui corporis architecto assumenda nostrum dolorem omnis. Ea aliquam quam eveniet perferendis aut sit. Alias quo explicabo nulla. Est nobis explicabo non voluptatem cumque quod omnis consequuntur voluptas. Culpa ea ut est aut aut incidunt id et ipsa. Aliquam atque expedita adipisci occaecati rerum animi. Reprehenderit hic qui assumenda perferendis.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Description = "Aut tempora deleniti provident tenetur illum tempore hic fugit laborum. Error ea totam voluptatem asperiores deserunt. Illum velit veniam necessitatibus impedit est atque possimus. Nisi ducimus fugiat rem quo id ab similique architecto velit. Quas aut tempore ex maxime ea ut vero. Et amet exercitationem aut sed perferendis doloremque mollitia voluptatem.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Description = "Quos cupiditate eos magni sit dicta incidunt totam. Qui sit eius et odio ipsam cupiditate odio. Reprehenderit mollitia deserunt quis illo rerum est facilis aperiam quam. Voluptas voluptatibus et voluptas excepturi. Quia animi delectus dolorum. Reprehenderit et harum cum qui quaerat soluta ab quas consequatur. Iusto sit eos tenetur ut aut id debitis ut quidem. Quod necessitatibus sunt voluptatem vel quas quasi inventore deleniti non.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Description = "Est nihil quas voluptas nostrum velit perspiciatis autem neque. Aut aut iste ab voluptas corrupti. Blanditiis velit quos hic facilis voluptatibus suscipit illo. Totam dolor minus incidunt aut dolor velit molestias ipsa debitis. Et impedit itaque qui nam placeat facilis consequatur laborum unde. Et dolore illum alias est eos maxime. Voluptatum sed vel at laborum quas iure deleniti.",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Description = "Et enim placeat distinctio. Aut eaque et non. Non natus expedita qui aut explicabo quia dolores. Id quo hic est molestias sint necessitatibus maxime cumque modi. Eveniet fuga expedita reiciendis debitis repellat laudantium voluptatum.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Description = "Doloribus ipsum mollitia consectetur qui cumque exercitationem ab. Ex aliquam eius quos occaecati unde ut repellendus accusantium aut. Omnis quas aperiam vel vel repellat provident. Sit quis accusamus qui libero amet dignissimos praesentium cupiditate maiores. Qui fuga minima qui porro temporibus ut impedit consequatur et.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Description = "Doloremque reiciendis explicabo dolores. Incidunt sit hic delectus ea facilis non praesentium cupiditate laborum. Error rerum at sit dolores reprehenderit rerum sit. Omnis ex deleniti sit laboriosam modi explicabo enim omnis sint. Quia nostrum necessitatibus assumenda quis ut quo saepe vero ut. Dolores quisquam voluptatem aut ut quis et eum. Facilis dolores incidunt enim nihil non deserunt. Laborum ipsum sint quia consequatur nihil et dolores.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            Description = "Quam dolore dolores ipsam molestiae ut error eaque. Minus voluptas consequuntur fugit magni eos. Quo et ut voluptas et laborum odio autem. Hic ut consequatur suscipit sed. Quo non occaecati labore eveniet ut aliquid alias sint dignissimos. Dolorem magni et veniam ab qui molestiae harum tempora.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            Description = "Dolorum similique temporibus aliquid et. Omnis porro dignissimos qui quaerat impedit quam. Dolore illo quia voluptas. Et est molestiae quibusdam magnam earum et dolores similique. Corporis ab ea eaque quod. Praesentium hic molestiae voluptatem cupiditate qui dolorum aliquid animi blanditiis. Eius nulla eaque placeat modi perferendis voluptatem et et.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            Description = "Nihil repellendus perspiciatis corporis et provident et sapiente est delectus. Voluptates animi similique sit. In voluptates in ab quaerat et illo possimus. Aut adipisci omnis est quam. Aliquid alias voluptatem distinctio deserunt odio temporibus facilis veritatis.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            Description = "Mollitia omnis incidunt officia porro in quam et. Blanditiis facere numquam eos tempora. Quibusdam quia a qui autem ab deserunt ea. Quo est omnis consequatur et et sapiente culpa doloribus omnis. Eum minus quaerat autem ratione.",
                            UserId = 25
                        });
                });

            modelBuilder.Entity("Flagging.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Maxime aut dolor eos possimus officia ea sed corporis.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Message = "Voluptates quasi corrupti velit consequuntur.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Message = "A quis et id sapiente.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Message = "Doloremque et enim enim harum eos natus sapiente dolor in.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Message = "Id rem vero eos recusandae.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Message = "Et dolore dolor vel quia in ut quos.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Message = "Eos et necessitatibus magni incidunt libero.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Message = "Id optio enim quasi voluptatibus ea quos laudantium vel velit placeat.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Message = "Animi et et qui qui.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Message = "Facilis reprehenderit odit ipsam consectetur cupiditate.",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Message = "Impedit error facilis autem occaecati eos ut occaecati expedita.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Message = "Eius error esse vel aut accusantium.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Message = "Aut reiciendis sit voluptas aut aspernatur et quae.",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Message = "Rerum cumque aut illum harum recusandae.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Message = "Ut praesentium sit est minus.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Message = "Tenetur ipsa fugit tenetur animi id id.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Message = "Vel maxime tempore consequatur sed.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Message = "Ad harum iste et odio quam nam alias aut doloribus.",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Message = "Sit ducimus repellat voluptatem assumenda nihil aut quia nihil.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Message = "Aut sit velit in pariatur aut nihil ut provident expedita et.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Message = "Quam nisi nobis velit similique ut neque dolor quia.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            Message = "Aut in et quis ea nesciunt earum tempore tenetur est omnis.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            Message = "Iste similique magni et quos et ea harum.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            Message = "Rem perferendis corrupti vel deserunt.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            Message = "Ipsa mollitia excepturi aliquid voluptates itaque error est illo et.",
                            UserId = 25
                        });
                });

            modelBuilder.Entity("Flagging.Data.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1981, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1929, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1961, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1979, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1983, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1920, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 4,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2002, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 4,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(1925, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 4,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(1927, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 4,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(1972, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 5,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(1924, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 5,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(1961, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(1968, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(1933, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 7,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(1982, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 9,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(1964, 8, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 9,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(1931, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 10,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(1912, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 10,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(1927, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 11,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(1982, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 12,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(1975, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 13,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(1980, 2, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 13,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(2004, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 14,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            DateCreated = new DateTime(2015, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 14,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            DateCreated = new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 15,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            DateCreated = new DateTime(1928, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 16,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            DateCreated = new DateTime(1938, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            DateCreated = new DateTime(1938, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            DateCreated = new DateTime(1974, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            DateCreated = new DateTime(1962, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            DateCreated = new DateTime(1964, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            DateCreated = new DateTime(1966, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 20,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            DateCreated = new DateTime(1903, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 21,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            DateCreated = new DateTime(1912, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 21,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            DateCreated = new DateTime(1963, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 22,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            DateCreated = new DateTime(1962, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            DateCreated = new DateTime(1962, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 24,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            DateCreated = new DateTime(1971, 8, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 24,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            DateCreated = new DateTime(2004, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 24,
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            DateCreated = new DateTime(2007, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 41,
                            DateCreated = new DateTime(1970, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            DateCreated = new DateTime(1936, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            DateCreated = new DateTime(1950, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 3,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            DateCreated = new DateTime(1969, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 4,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            DateCreated = new DateTime(1954, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 5,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            DateCreated = new DateTime(1981, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 5,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 47,
                            DateCreated = new DateTime(1956, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 5,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 48,
                            DateCreated = new DateTime(1925, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 49,
                            DateCreated = new DateTime(1971, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 50,
                            DateCreated = new DateTime(1967, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 7,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 51,
                            DateCreated = new DateTime(2018, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 8,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 52,
                            DateCreated = new DateTime(2010, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 10,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 53,
                            DateCreated = new DateTime(1958, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 10,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 54,
                            DateCreated = new DateTime(1953, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 11,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 55,
                            DateCreated = new DateTime(1951, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 12,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 56,
                            DateCreated = new DateTime(1962, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 13,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 57,
                            DateCreated = new DateTime(1992, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 13,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 58,
                            DateCreated = new DateTime(1958, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 16,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 59,
                            DateCreated = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 60,
                            DateCreated = new DateTime(2014, 9, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 61,
                            DateCreated = new DateTime(2007, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 62,
                            DateCreated = new DateTime(1994, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 18,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 63,
                            DateCreated = new DateTime(1983, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 64,
                            DateCreated = new DateTime(1921, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 65,
                            DateCreated = new DateTime(2004, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 66,
                            DateCreated = new DateTime(1994, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 67,
                            DateCreated = new DateTime(1951, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 68,
                            DateCreated = new DateTime(1942, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 21,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 69,
                            DateCreated = new DateTime(1960, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 70,
                            DateCreated = new DateTime(2012, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 71,
                            DateCreated = new DateTime(1976, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 72,
                            DateCreated = new DateTime(1935, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 25,
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 73,
                            DateCreated = new DateTime(1943, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 74,
                            DateCreated = new DateTime(1949, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 75,
                            DateCreated = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 2,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 76,
                            DateCreated = new DateTime(1916, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 3,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 77,
                            DateCreated = new DateTime(1962, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 5,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 78,
                            DateCreated = new DateTime(1962, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 79,
                            DateCreated = new DateTime(1982, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 80,
                            DateCreated = new DateTime(1975, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 81,
                            DateCreated = new DateTime(1998, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 7,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 82,
                            DateCreated = new DateTime(1977, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 7,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 83,
                            DateCreated = new DateTime(1962, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 84,
                            DateCreated = new DateTime(1904, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 85,
                            DateCreated = new DateTime(1998, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 86,
                            DateCreated = new DateTime(1961, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 87,
                            DateCreated = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 88,
                            DateCreated = new DateTime(2013, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 89,
                            DateCreated = new DateTime(1934, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 90,
                            DateCreated = new DateTime(1943, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 10,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 91,
                            DateCreated = new DateTime(1952, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 11,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 92,
                            DateCreated = new DateTime(1966, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 11,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 93,
                            DateCreated = new DateTime(2001, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 11,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 94,
                            DateCreated = new DateTime(1955, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 12,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 95,
                            DateCreated = new DateTime(1941, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 14,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 96,
                            DateCreated = new DateTime(1972, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 14,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 97,
                            DateCreated = new DateTime(1962, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 15,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 98,
                            DateCreated = new DateTime(1983, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 16,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 99,
                            DateCreated = new DateTime(1962, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 16,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 100,
                            DateCreated = new DateTime(1977, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 101,
                            DateCreated = new DateTime(2017, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 102,
                            DateCreated = new DateTime(1949, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 17,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 103,
                            DateCreated = new DateTime(1962, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 18,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 104,
                            DateCreated = new DateTime(2006, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 18,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 105,
                            DateCreated = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 18,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 106,
                            DateCreated = new DateTime(1958, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 107,
                            DateCreated = new DateTime(2001, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 19,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 108,
                            DateCreated = new DateTime(2013, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 109,
                            DateCreated = new DateTime(1961, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 110,
                            DateCreated = new DateTime(1916, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 111,
                            DateCreated = new DateTime(1925, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 22,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 112,
                            DateCreated = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 22,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 113,
                            DateCreated = new DateTime(1946, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 114,
                            DateCreated = new DateTime(1995, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 115,
                            DateCreated = new DateTime(1925, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 116,
                            DateCreated = new DateTime(1986, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 117,
                            DateCreated = new DateTime(1966, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 118,
                            DateCreated = new DateTime(1923, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 24,
                            Status = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Flagging.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Tracy",
                            LastName = "Williamson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Mariane",
                            LastName = "Fritsch"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Haleigh",
                            LastName = "Pouros"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Marilou",
                            LastName = "Emard"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Luther",
                            LastName = "Fritsch"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Hyman",
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "German",
                            LastName = "Bauch"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Emily",
                            LastName = "Armstrong"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Candelario",
                            LastName = "Schoen"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Michale",
                            LastName = "Purdy"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Marco",
                            LastName = "Spinka"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Carlee",
                            LastName = "O'Keefe"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Keith",
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Kale",
                            LastName = "Hackett"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Keyon",
                            LastName = "Rath"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Celestino",
                            LastName = "Reilly"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Felipe",
                            LastName = "Macejkovic"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Rose",
                            LastName = "Treutel"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Easter",
                            LastName = "Raynor"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Cyrus",
                            LastName = "Jacobi"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Delores",
                            LastName = "Brekke"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Damien",
                            LastName = "Gislason"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Aleen",
                            LastName = "Botsford"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Carlotta",
                            LastName = "D'Amore"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Berenice",
                            LastName = "Blick"
                        });
                });

            modelBuilder.Entity("Flagging.Data.Article", b =>
                {
                    b.HasOne("Flagging.Data.Article", null)
                        .WithMany("Articles")
                        .HasForeignKey("ArticleId");

                    b.HasOne("Flagging.Data.User", null)
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flagging.Data.Comment", b =>
                {
                    b.HasOne("Flagging.Data.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flagging.Data.Flag", b =>
                {
                    b.HasOne("Flagging.Data.Article", "Article")
                        .WithMany("ReportFlags")
                        .HasForeignKey("ItemId");

                    b.HasOne("Flagging.Data.Comment", "Comment")
                        .WithMany("ReportFlags")
                        .HasForeignKey("ItemId");

                    b.HasOne("Flagging.Data.User", "ReportedUser")
                        .WithMany("ReportFlags")
                        .HasForeignKey("ItemId");

                    b.Navigation("Article");

                    b.Navigation("Comment");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("Flagging.Data.Article", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("ReportFlags");
                });

            modelBuilder.Entity("Flagging.Data.Comment", b =>
                {
                    b.Navigation("ReportFlags");
                });

            modelBuilder.Entity("Flagging.Data.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("ReportFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
