// <auto-generated />
using System;
using Flagging.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flagging.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231107083354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flagging.Data.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Libero facilis aspernatur enim blanditiis. Aut eos impedit voluptatem placeat provident. Qui quo doloremque illo porro omnis cupiditate facilis consectetur. Et reprehenderit pariatur perferendis distinctio voluptas enim iste neque eos. Alias possimus id deserunt perferendis. Quisquam ea ut est maiores. Consequuntur voluptatem et delectus est nemo rerum natus. Illum accusamus ipsum odit voluptas.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Consequatur sunt velit nihil possimus cupiditate deleniti harum. Laboriosam nobis quis minus qui blanditiis. Dolore quae deleniti cum sit illum quidem eveniet. Dolor aut et et fugiat. Earum consequatur nam a quo quia quia id. Veniam sed rerum quasi accusamus explicabo consequatur temporibus voluptatem. Ullam eligendi quae suscipit amet.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Magnam vitae repellat soluta facere repudiandae ducimus deleniti iure. Ducimus tempore velit ut. Quas maxime exercitationem ut voluptas in vero illo dolorem. Beatae et et quidem quis corrupti nemo ea qui. Dolor sit est et sapiente. Et nulla voluptatum placeat perspiciatis voluptas similique debitis. Unde minus enim cupiditate aut.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dolor non autem autem molestias pariatur commodi placeat. Nulla corrupti quo saepe. Dolor aspernatur harum aut amet aliquid. Dolor beatae veniam quia voluptas in provident enim vero. Sed et debitis optio repellendus reiciendis maiores aut velit. Exercitationem animi molestias voluptatibus ut voluptas deleniti distinctio facere.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Eligendi fugiat perferendis quibusdam. Exercitationem velit beatae ea. Praesentium alias blanditiis ad culpa minima nemo dignissimos optio voluptas. In quia quae inventore quam omnis est. Nostrum rerum facilis repellendus ad molestiae. Soluta qui ut consequuntur sint qui recusandae eum et. Et sed et sint. Et voluptas enim voluptas non.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ipsa nobis eius dolorem quo vero rem. Ipsum id ea rerum officiis velit perspiciatis aut. Quam saepe sunt dolores ea. Fugiat qui ullam consequatur consequatur cupiditate rerum perspiciatis eum soluta. Sit quia nemo maxime in aliquam sint officiis molestiae consequatur. Expedita sit qui et dolorem dolorem ut nobis.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nam dolore illo voluptatibus omnis recusandae aut unde. Enim omnis autem quia architecto at et. Reiciendis rem et voluptas exercitationem autem nisi vitae vero. Quo rerum corporis rerum deleniti ut. Tempore temporibus nihil ullam. Ea architecto non porro reprehenderit est. Voluptates maiores similique voluptas nihil. Voluptatem distinctio maxime corrupti.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Consequatur neque ea nostrum. Eum est laudantium rerum nihil sit optio quasi rerum nihil. Laboriosam excepturi ipsum qui eos veniam nostrum non. Est itaque quae magnam et culpa. Perspiciatis natus voluptas dolores eum sit. Laboriosam at repellendus aut qui necessitatibus aut.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Doloremque voluptas repudiandae alias dolorem. Voluptatem ut eligendi est in est dolorem. Blanditiis autem quia quidem mollitia voluptatem doloribus cumque et dolor. Est error cumque dicta debitis repudiandae necessitatibus alias porro cumque. Consequatur ut nam eligendi eos consequatur et quisquam.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Quaerat maiores eum et temporibus blanditiis quidem sed similique corrupti. Porro nesciunt voluptas porro autem autem dolor cumque ea quod. Voluptatem maxime illo quidem velit accusamus quia dolorem dolorum. Esse corrupti quis ut. Qui dolor unde fuga officia modi ut nihil. Esse voluptas vel voluptatem qui aperiam voluptatem placeat consequatur dolores.",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Description = "Enim soluta ut amet voluptas cum qui saepe quo cupiditate. Sunt a illum est vitae rerum dolore tempore voluptatem autem. Mollitia repellat accusantium vitae suscipit. Quia sequi dolores earum qui. Magnam vel magnam itaque. Sed ut tempora quis.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Description = "Voluptas et est soluta eveniet aut nobis. Recusandae fugit consequatur ab. Consequatur et quidem et ipsa saepe aut. Ipsam expedita sequi inventore aliquam similique assumenda fugiat inventore. Quidem laborum ipsum reiciendis omnis voluptate porro animi. Qui pariatur quasi tenetur eum qui sequi voluptatem culpa. Hic rem veritatis quod dolores omnis. Dolorem accusantium omnis eum et ipsum.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Description = "Doloremque sit eum nisi molestias recusandae laboriosam omnis. Similique debitis doloremque quis in non et. Eum ipsa sed suscipit repellat. Aut iste exercitationem harum. Tempore quo quaerat incidunt rem et ratione porro dolorum. Earum perferendis deleniti suscipit soluta exercitationem dolor aliquid ut consectetur. Qui non ipsum repellat. Deleniti quia iure quis et veritatis.",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Description = "Excepturi amet pariatur eveniet. Velit nulla autem voluptatem aperiam sint mollitia eum sit vero. Tempora facere nobis corrupti optio est facere eaque. Qui qui sequi in non ut. Eveniet maxime alias similique a nobis corporis consequatur omnis aperiam.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Description = "Debitis est ea et asperiores aliquid dolor. Esse ut dolor quisquam ipsa quam est assumenda aut. Ex voluptas provident beatae rerum minima sit reiciendis ut cupiditate. Quam reiciendis vitae impedit odio accusantium ipsa quo. Iure deserunt corrupti inventore voluptates quod officia accusamus beatae aut. Odit nesciunt aut cupiditate. Ea eum dolorum aut qui eligendi consequuntur.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Description = "Ut doloremque quia culpa tempore. Tenetur soluta voluptate ad. Magnam cupiditate labore ut id delectus libero accusantium. Et qui consequatur non natus inventore. Placeat consequatur voluptates repellat.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ullam unde nulla autem sapiente expedita. Mollitia atque et quod eius modi et hic maiores. Quibusdam sunt laboriosam ut earum nostrum temporibus repellendus dicta. Qui voluptatibus commodi in aut voluptatem maiores autem. Ut quidem sint quod sint et.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Description = "Beatae voluptatem omnis vitae repellendus dignissimos molestiae omnis amet et. Non vero quod ratione exercitationem placeat a illo adipisci nihil. Eaque eos eos aut dicta et. Deserunt ea debitis eos iusto ullam adipisci eos optio qui. Illo atque mollitia cum ex qui error repellendus.",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Description = "Nulla sapiente velit excepturi iusto. Commodi accusamus veniam fugiat sed est nesciunt dolorem deserunt. Et incidunt ipsam molestias exercitationem. Molestias deleniti veritatis autem minus nisi qui quia. Placeat adipisci minima mollitia labore cupiditate. Voluptatem rem beatae perspiciatis optio itaque accusamus. Laudantium quos amet quia non. A tenetur cum dicta illo quaerat et itaque.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Description = "A exercitationem et consequuntur quia. Non qui aut perspiciatis placeat aut corrupti quo cumque. Quia occaecati dolores fuga. Necessitatibus accusamus occaecati ducimus illum sequi ab esse. Vel perspiciatis voluptatum fugit aliquid in. Molestias excepturi consequatur provident quae consequatur totam.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Description = "Debitis ipsam optio atque voluptatibus nisi. Et aliquam perspiciatis facilis corrupti nemo et eius. Quis nobis repellat aperiam. Eum doloremque nulla mollitia harum suscipit voluptate occaecati. Repellat voluptate asperiores maiores non praesentium perferendis aut. Quos soluta illo deserunt vitae. Asperiores neque temporibus totam et aperiam perspiciatis odio.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            Description = "Hic temporibus sequi occaecati deleniti eos. Iure sit ipsum ullam. Dolores et illo perspiciatis reprehenderit perferendis aut consequuntur magni aspernatur. Tenetur aut a repellat soluta. Consequatur corporis delectus ut praesentium. Dicta non voluptas voluptatibus recusandae aut aspernatur a est nemo.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            Description = "Quasi similique aut beatae quaerat officia explicabo. Inventore magni nemo repellat architecto ut et doloremque illo similique. Quia non quidem rerum et omnis veniam provident vero ad. Perferendis sit consequatur blanditiis. Inventore ea id molestias cumque placeat illo. Impedit aut qui sit harum sunt voluptates consequatur nisi. Ut recusandae possimus incidunt pariatur corrupti aut voluptate recusandae doloremque.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            Description = "Ipsa nam quis rerum quam aspernatur exercitationem qui dicta dolor. Odit dolore voluptas nostrum beatae aut neque nobis suscipit qui. Quia laboriosam possimus voluptatem temporibus ut nobis est deleniti corrupti. Est ex sit voluptatem fugit dolorem sit nemo debitis. Voluptatibus sint repudiandae velit debitis vel beatae. Error reprehenderit iste soluta quo debitis delectus. Quos repellendus rerum eaque in eius aut rerum sit sed.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            Description = "Nihil veritatis a et eveniet. Reiciendis dignissimos ad aliquid rerum praesentium architecto. Impedit sed et quisquam doloribus. Sit iusto optio sapiente. Ipsam quidem eos harum qui nisi alias aliquid quasi.",
                            UserId = 25
                        });
                });

            modelBuilder.Entity("Flagging.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "Fugiat repellendus ut rem et animi et sapiente rerum expedita ipsa.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Message = "Quasi minima consequuntur reiciendis quidem nam aut nisi expedita.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Message = "Odit aut dolorem est eligendi esse quae aspernatur sint omnis quia.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Message = "Accusantium voluptas veniam rerum minus.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Message = "Minus amet officiis quis fuga mollitia.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Message = "Provident atque quaerat ut possimus et suscipit quaerat voluptates quam dolore.",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Message = "Delectus nihil occaecati sunt molestias ea eius nostrum similique.",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Message = "Debitis provident dolorem ut odit architecto facere facere aliquam.",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Message = "Architecto est quo rerum molestias recusandae temporibus sint inventore quisquam aut.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Message = "Quis ea ut dolorem nostrum aut porro iste dolor et.",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Message = "Alias blanditiis aspernatur explicabo soluta.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Message = "Et minus laborum dolores et in rerum.",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Message = "Fugiat accusantium quae ullam libero.",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Message = "Iste omnis aut esse quasi deserunt voluptas.",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Message = "Harum dicta nam recusandae ratione autem quo molestiae est.",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Message = "Minus soluta magnam non et qui.",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Message = "Tempora debitis praesentium eveniet ut inventore rerum quisquam beatae deserunt placeat.",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Message = "Tempore sequi quidem cumque rem ullam aut.",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Message = "Aut exercitationem cupiditate id eveniet.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Message = "Iure modi ut voluptatem necessitatibus et reprehenderit.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Message = "Dicta voluptatem autem vitae ea molestiae delectus cum.",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            Message = "Dolorem architecto eos autem enim rem quia earum atque illum tempora.",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            Message = "Velit tempore et occaecati dolore.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            Message = "Ut incidunt sint magnam sit illo.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            Message = "Culpa omnis molestias aut debitis nihil quia cumque magni id.",
                            UserId = 25
                        });
                });

            modelBuilder.Entity("Flagging.Data.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReportedUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CommentId");

                    b.HasIndex("ReportedUserId");

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 2,
                            DateCreated = new DateTime(1978, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            DateCreated = new DateTime(1919, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 4,
                            DateCreated = new DateTime(2002, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 4,
                            DateCreated = new DateTime(1964, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 4,
                            DateCreated = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 4,
                            DateCreated = new DateTime(1962, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 5,
                            DateCreated = new DateTime(1914, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 5,
                            DateCreated = new DateTime(1956, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 5,
                            DateCreated = new DateTime(1963, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 6,
                            DateCreated = new DateTime(1965, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            ArticleId = 7,
                            DateCreated = new DateTime(1914, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            ArticleId = 7,
                            DateCreated = new DateTime(1962, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            ArticleId = 8,
                            DateCreated = new DateTime(1959, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            ArticleId = 8,
                            DateCreated = new DateTime(1922, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            ArticleId = 9,
                            DateCreated = new DateTime(1997, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            ArticleId = 9,
                            DateCreated = new DateTime(1969, 8, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            ArticleId = 10,
                            DateCreated = new DateTime(2018, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            ArticleId = 10,
                            DateCreated = new DateTime(2010, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            ArticleId = 10,
                            DateCreated = new DateTime(1977, 9, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            ArticleId = 10,
                            DateCreated = new DateTime(1965, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            ArticleId = 11,
                            DateCreated = new DateTime(1917, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            ArticleId = 11,
                            DateCreated = new DateTime(1927, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            ArticleId = 12,
                            DateCreated = new DateTime(1926, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            ArticleId = 12,
                            DateCreated = new DateTime(1958, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            ArticleId = 13,
                            DateCreated = new DateTime(1927, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            ArticleId = 14,
                            DateCreated = new DateTime(1969, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            ArticleId = 14,
                            DateCreated = new DateTime(1912, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            ArticleId = 15,
                            DateCreated = new DateTime(1950, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            ArticleId = 17,
                            DateCreated = new DateTime(1956, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            ArticleId = 17,
                            DateCreated = new DateTime(2011, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            ArticleId = 18,
                            DateCreated = new DateTime(1973, 12, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            ArticleId = 19,
                            DateCreated = new DateTime(1932, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            ArticleId = 19,
                            DateCreated = new DateTime(1979, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            ArticleId = 19,
                            DateCreated = new DateTime(1905, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            ArticleId = 19,
                            DateCreated = new DateTime(1987, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            ArticleId = 20,
                            DateCreated = new DateTime(1936, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            ArticleId = 20,
                            DateCreated = new DateTime(2017, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            ArticleId = 21,
                            DateCreated = new DateTime(1965, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            ArticleId = 21,
                            DateCreated = new DateTime(1965, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            ArticleId = 21,
                            DateCreated = new DateTime(1919, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            ArticleId = 22,
                            DateCreated = new DateTime(1953, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            ArticleId = 22,
                            DateCreated = new DateTime(1984, 8, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            ArticleId = 22,
                            DateCreated = new DateTime(1957, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            ArticleId = 23,
                            DateCreated = new DateTime(1947, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            ArticleId = 23,
                            DateCreated = new DateTime(1932, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            ArticleId = 23,
                            DateCreated = new DateTime(1922, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            ArticleId = 25,
                            DateCreated = new DateTime(1982, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            ArticleId = 25,
                            DateCreated = new DateTime(1962, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            ArticleId = 25,
                            DateCreated = new DateTime(1951, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            ArticleId = 25,
                            DateCreated = new DateTime(1964, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 51,
                            CommentId = 1,
                            DateCreated = new DateTime(1962, 5, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 52,
                            CommentId = 1,
                            DateCreated = new DateTime(1901, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 53,
                            CommentId = 1,
                            DateCreated = new DateTime(1961, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 54,
                            CommentId = 1,
                            DateCreated = new DateTime(1962, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 55,
                            CommentId = 2,
                            DateCreated = new DateTime(2000, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 56,
                            CommentId = 2,
                            DateCreated = new DateTime(1965, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 57,
                            CommentId = 3,
                            DateCreated = new DateTime(1911, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 58,
                            CommentId = 3,
                            DateCreated = new DateTime(1973, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 59,
                            CommentId = 4,
                            DateCreated = new DateTime(2000, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 60,
                            CommentId = 4,
                            DateCreated = new DateTime(1959, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 61,
                            CommentId = 4,
                            DateCreated = new DateTime(1924, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 62,
                            CommentId = 5,
                            DateCreated = new DateTime(1969, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 63,
                            CommentId = 5,
                            DateCreated = new DateTime(1919, 2, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 64,
                            CommentId = 5,
                            DateCreated = new DateTime(1967, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 65,
                            CommentId = 6,
                            DateCreated = new DateTime(1957, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 66,
                            CommentId = 6,
                            DateCreated = new DateTime(1932, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 67,
                            CommentId = 7,
                            DateCreated = new DateTime(1944, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 68,
                            CommentId = 8,
                            DateCreated = new DateTime(1987, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 69,
                            CommentId = 9,
                            DateCreated = new DateTime(1981, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 70,
                            CommentId = 9,
                            DateCreated = new DateTime(1970, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 71,
                            CommentId = 9,
                            DateCreated = new DateTime(1931, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 72,
                            CommentId = 9,
                            DateCreated = new DateTime(1910, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 73,
                            CommentId = 9,
                            DateCreated = new DateTime(1965, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 74,
                            CommentId = 10,
                            DateCreated = new DateTime(1973, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 75,
                            CommentId = 10,
                            DateCreated = new DateTime(1996, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 76,
                            CommentId = 10,
                            DateCreated = new DateTime(1994, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 77,
                            CommentId = 11,
                            DateCreated = new DateTime(1967, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 78,
                            CommentId = 11,
                            DateCreated = new DateTime(1974, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 79,
                            CommentId = 12,
                            DateCreated = new DateTime(2012, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 80,
                            CommentId = 13,
                            DateCreated = new DateTime(1993, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 81,
                            CommentId = 13,
                            DateCreated = new DateTime(1975, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 82,
                            CommentId = 13,
                            DateCreated = new DateTime(1962, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 83,
                            CommentId = 14,
                            DateCreated = new DateTime(1962, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 84,
                            CommentId = 15,
                            DateCreated = new DateTime(1962, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 85,
                            CommentId = 15,
                            DateCreated = new DateTime(1972, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 86,
                            CommentId = 15,
                            DateCreated = new DateTime(1935, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 87,
                            CommentId = 16,
                            DateCreated = new DateTime(1975, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 88,
                            CommentId = 18,
                            DateCreated = new DateTime(1930, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 89,
                            CommentId = 18,
                            DateCreated = new DateTime(1939, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 90,
                            CommentId = 18,
                            DateCreated = new DateTime(1962, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 91,
                            CommentId = 19,
                            DateCreated = new DateTime(1940, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 92,
                            CommentId = 19,
                            DateCreated = new DateTime(1902, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 93,
                            CommentId = 20,
                            DateCreated = new DateTime(1978, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 94,
                            CommentId = 21,
                            DateCreated = new DateTime(2011, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 95,
                            CommentId = 22,
                            DateCreated = new DateTime(1912, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 96,
                            CommentId = 23,
                            DateCreated = new DateTime(1910, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 97,
                            CommentId = 23,
                            DateCreated = new DateTime(1916, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 98,
                            CommentId = 24,
                            DateCreated = new DateTime(1987, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 99,
                            CommentId = 24,
                            DateCreated = new DateTime(1962, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 100,
                            CommentId = 24,
                            DateCreated = new DateTime(1952, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 101,
                            CommentId = 25,
                            DateCreated = new DateTime(1962, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 102,
                            CommentId = 25,
                            DateCreated = new DateTime(2015, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 103,
                            CommentId = 25,
                            DateCreated = new DateTime(1978, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 104,
                            DateCreated = new DateTime(1997, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 1,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 105,
                            DateCreated = new DateTime(1980, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 1,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 106,
                            DateCreated = new DateTime(1935, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 2,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 107,
                            DateCreated = new DateTime(1973, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 2,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 108,
                            DateCreated = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 2,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 109,
                            DateCreated = new DateTime(2014, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 2,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 110,
                            DateCreated = new DateTime(2017, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 5,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 111,
                            DateCreated = new DateTime(1971, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 6,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 112,
                            DateCreated = new DateTime(2012, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 7,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 113,
                            DateCreated = new DateTime(1910, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 7,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 114,
                            DateCreated = new DateTime(1956, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 115,
                            DateCreated = new DateTime(1990, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 116,
                            DateCreated = new DateTime(1982, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 117,
                            DateCreated = new DateTime(1951, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 118,
                            DateCreated = new DateTime(1967, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 8,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 119,
                            DateCreated = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 120,
                            DateCreated = new DateTime(1915, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 121,
                            DateCreated = new DateTime(1991, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 9,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 122,
                            DateCreated = new DateTime(1971, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 10,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 123,
                            DateCreated = new DateTime(1911, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 10,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 124,
                            DateCreated = new DateTime(1962, 9, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 11,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 125,
                            DateCreated = new DateTime(1964, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 12,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 126,
                            DateCreated = new DateTime(1959, 12, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 12,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 127,
                            DateCreated = new DateTime(1962, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 12,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 128,
                            DateCreated = new DateTime(1943, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 13,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 129,
                            DateCreated = new DateTime(1978, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 14,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 130,
                            DateCreated = new DateTime(1935, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 14,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 131,
                            DateCreated = new DateTime(1944, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 14,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 132,
                            DateCreated = new DateTime(1962, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 15,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 133,
                            DateCreated = new DateTime(1962, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 16,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 134,
                            DateCreated = new DateTime(1973, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 16,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 135,
                            DateCreated = new DateTime(2009, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 17,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 136,
                            DateCreated = new DateTime(1990, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 17,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 137,
                            DateCreated = new DateTime(1907, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 17,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 138,
                            DateCreated = new DateTime(1953, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 18,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 139,
                            DateCreated = new DateTime(1959, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 19,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 140,
                            DateCreated = new DateTime(2006, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 141,
                            DateCreated = new DateTime(2015, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 142,
                            DateCreated = new DateTime(1940, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 143,
                            DateCreated = new DateTime(1918, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 144,
                            DateCreated = new DateTime(1986, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 20,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 145,
                            DateCreated = new DateTime(2002, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 21,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 146,
                            DateCreated = new DateTime(1963, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 22,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 147,
                            DateCreated = new DateTime(1962, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 148,
                            DateCreated = new DateTime(1976, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 149,
                            DateCreated = new DateTime(2008, 8, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 150,
                            DateCreated = new DateTime(1982, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 23,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 151,
                            DateCreated = new DateTime(1962, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 24,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 152,
                            DateCreated = new DateTime(1971, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 24,
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 153,
                            DateCreated = new DateTime(1908, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReportedUserId = 24,
                            Status = 0,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Flagging.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Linda",
                            LastName = "Swift"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Thora",
                            LastName = "Welch"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Trevor",
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Lew",
                            LastName = "Grady"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jarred",
                            LastName = "Waelchi"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Marianna",
                            LastName = "Swaniawski"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Noemie",
                            LastName = "Corkery"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Dillan",
                            LastName = "Gottlieb"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Vida",
                            LastName = "Stamm"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Jasmin",
                            LastName = "Bednar"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Hallie",
                            LastName = "Boehm"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Darrel",
                            LastName = "Streich"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Margarett",
                            LastName = "Fisher"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Patience",
                            LastName = "Mraz"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Ken",
                            LastName = "Collins"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Joannie",
                            LastName = "Abernathy"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Keenan",
                            LastName = "Klocko"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Herman",
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Oda",
                            LastName = "Greenholt"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Marlen",
                            LastName = "Ebert"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Pearlie",
                            LastName = "Barton"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Amos",
                            LastName = "Haley"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Markus",
                            LastName = "Bartell"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Brady",
                            LastName = "Heller"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Theodore",
                            LastName = "Rohan"
                        });
                });

            modelBuilder.Entity("Flagging.Data.Article", b =>
                {
                    b.HasOne("Flagging.Data.Article", null)
                        .WithMany("Articles")
                        .HasForeignKey("ArticleId");

                    b.HasOne("Flagging.Data.User", null)
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flagging.Data.Comment", b =>
                {
                    b.HasOne("Flagging.Data.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flagging.Data.Flag", b =>
                {
                    b.HasOne("Flagging.Data.Article", "Article")
                        .WithMany("ReportFlags")
                        .HasForeignKey("ArticleId");

                    b.HasOne("Flagging.Data.Comment", "Comment")
                        .WithMany("ReportFlags")
                        .HasForeignKey("CommentId");

                    b.HasOne("Flagging.Data.User", "ReportedUser")
                        .WithMany("ReportFlags")
                        .HasForeignKey("ReportedUserId");

                    b.Navigation("Article");

                    b.Navigation("Comment");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("Flagging.Data.Article", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("ReportFlags");
                });

            modelBuilder.Entity("Flagging.Data.Comment", b =>
                {
                    b.Navigation("ReportFlags");
                });

            modelBuilder.Entity("Flagging.Data.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("ReportFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
